### ISSUE TITLE
0.96版本开始，saswell/climate 组件import SUPPORT_AWAY_MODE, SUPPORT_ON_OFF 报错

### ISSUE THREAD

**Issue by xia0linz1** [Yonsm/HAExtra#9]
从0.96版本开始，saswell/climate 组件 from homeassistant.components.climate.const import (SUPPORT_AWAY_MODE, SUPPORT_ON_OFF) 报错。
检查const.py确实没有了SUPPORT_AWAY_MODE,和SUPPORT_ON_OFF，搜不到官方文档描述这个sh*t操作，求指教

**Comment by xia0linz1** [comment]
已修复，谢谢更新

**Comment by Yonsm** [comment]
感谢反馈，我只是没有那么及时跟进
